name: Feature Request
description: Suggest an improvement or new capability
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. A good feature request explains the problem it solves, not just the solution.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the situation where you feel something is missing or frustrating.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like to see?
      description: Describe your proposed solution or behaviour.
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Which area does this relate to?
      options:
        - Canvas / diagram editing
        - Inspector
        - Toolbar
        - DSL support
        - View types
        - Export
        - VS Code integration
        - Browser app
        - Documentation
        - Other
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you have considered
      description: Any workarounds you currently use, or alternative approaches you thought about.
    validations:
      required: false
